### ISSUE TITLE
circular dependency on itself error with 9.0.0-rc.5 but not 9.0.0-rc.4 

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1508]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

With 9.0.0-rc.5 (and also 9.0.0-rc.6) I am getting

ERROR: Entry point @acoustic-content-sdk/api has a circular dependency on itself.

Although the package in question for sure does not have a dependency on itself. The same works fine with 9.0.0-rc.4

```
ng-packagr:            9.0.0-rc.6
@angular/compiler:     9.0.0-rc.8
rollup:                1.29.0
tsickle:               0.38.0
typescript:            3.7.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by CarstenLeue** [comment]
My package is using a yarn monorepo and an extension to the tsconfig.
Invoked like this:

`"build:packagr": "ng-packagr -p package.json -c tsconfig.json",`

with the custom config:

```json
{"extends":"../tsconfig.settings.json"}
```

and the parent setting

```json
{
  "extends": "../node_modules/ng-packagr/lib/ts/conf/tsconfig.ngc.json",
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true,
    "annotateForClosureCompiler": true
  }
}
```

**Comment by CarstenLeue** [comment]
with logging

```bash
ng-packagr -p package.json -c tsconfig.json
Building Angular Package
[debug] Found primary entry point: @acoustic-content-sdk/api
[debug] rimraf C:\d\prod-wch-sdk-ng9\packages\api\dist
[debug] Initializing tsconfig for @acoustic-content-sdk/api
[debug] Analysing sources for @acoustic-content-sdk/api
[debug] Found entry point dependency: @acoustic-content-sdk/api -> @acoustic-content-sdk/api
ERROR: Entry point @acoustic-content-sdk/api has a circular dependency on itself.
Error: Entry point @acoustic-content-sdk/api has a circular dependency on itself.
    at C:\d\prod-wch-sdk-ng9\node_modules\ng-packagr\lib\ng-package\entry-point\analyse-sources.transform.js:90:27
    at Generator.next (<anonymous>)
    at fulfilled (C:\d\prod-wch-sdk-ng9\node_modules\ng-packagr\lib\ng-package\entry-point\analyse-sources.transform.js:5:58)
```

**Comment by alan-agius4** [comment]
@CarstenLeue, kindly share a reproduction. Thanks.

**Comment by alan-agius4** [comment]
Or maybe it would be helpful to do a `grep` In the entire tree for `@acoustic-content-sdk/api` just to see were that entry point is being referenced.

**Comment by CarstenLeue** [comment]
@alan-agius4 I added some console logs to ng-packagr. 

It looks like the issue is in `ng-package\entry-point\analyse-sources.transform.js`. 

In `analyseEntryPoint` I added this debugging statement:

```js
            while (token !== ts.SyntaxKind.EndOfFileToken) {
                if (token === ts.SyntaxKind.ImportKeyword || token === ts.SyntaxKind.ExportKeyword) {
                    while (token !== ts.SyntaxKind.StringLiteral && token !== ts.SyntaxKind.EndOfFileToken) {
                        token = scanner.scan();
                    }
                    const moduleName = scanner.getTokenValue();
                    // Child Entry points need to start with primary entrypoint
                    if (moduleName.startsWith(packageNode.data.primary.moduleId)) {
						console.log('Carsten', filePath, moduleName, packageNode.data.primary.moduleId);
                        potentialDependencies.add(moduleName);
                    }
                }
                token = scanner.scan();
            }
```

Because this adds a dependency on itself to `potentialDependencies` and that finally causes the error.

The output is:

```bash
Carsten C:/d/prod-wch-sdk-ng9/packages/api/src/version.ts @acoustic-content-sdk/api @acoustic-content-sdk/api
```

so apparently it found `moduleName` to be `@acoustic-content-sdk/api` and that matches the package name. 

But the mentioned source file `C:/d/prod-wch-sdk-ng9/packages/api/src/version.ts` looks like this:

```ts
/** Version and build number of the package */
export const VERSION = {version: {major: '9', minor: '0', patch: '0'}, build: new Date(1578490257973)};
/** Module name */
export const MODULE = '@acoustic-content-sdk/api';
```

There is no import in that file.

**Comment by alan-agius4** [comment]
Thanks will take a look.

**Comment by CarstenLeue** [comment]
I also traced the current `token` and it is `10`, i.e. `StringLiteral`. 
My best guess is that `export const MODULE = '@acoustic-content-sdk/api';` is mistakenly interpreted as an import statement.

**Comment by CarstenLeue** [comment]
Indeed, changing the statement to `export const MODULE = '[@acoustic-content-sdk/api]';` does not cause the error.

**Comment by CarstenLeue** [comment]
To reproduce create a `ts` file with a constant value that matches the package name.

**Comment by alan-agius4** [comment]
Fixed and will be available on npm in a couple of mins.

**Comment by CarstenLeue** [comment]
Awesome, I confirm that this fixes the issue.

**Comment by nickwinger** [comment]
I still have this issue with version 9.1.3:
```
[error] Error: Entry point ng-swiss-army-knife has a circular dependency on itself.
    at analyseEntryPoint (D:\dev\ng-swiss-army-knife\node_modules\ng-packagr\lib\ng-package\entry-point\analyse-sources.transform.js:75:23)
    at MapSubscriber.project (D:\dev\ng-swiss-army-knife\node_modules\ng-packagr\lib\ng-package\entry-point\analyse-sources.transform.js:14:9)
    at MapSubscriber._next (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\operators\switchMap.js:89:26)
    at InnerSubscriber._next (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MapSubscriber._next (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\Subscriber.js:66:18)
    at D:\dev\ng-swiss-army-knife\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
```
I have an angular module where in den entry file i export validator and helpers.
In one validator file i use a helper function, somehow this is not allowed....
